name: emoji-art
channels:
  - defaults
dependencies:
  - mkl>=2018,<2019
  - pip>=9.0.1,<=18.1
  - python=3.6.*
  - scipy=1
  - pip:
      - black
      - colorama==0.3.9
      - numpy>=1.14.1,<=1.16
      - Pillow>=5.1.0,<=5.4.0
      - tqdm==4.23.4
